### ISSUE TITLE
Create .md files for papers

### ISSUE THREAD

**Issue by BGerwe** [UW-SSEEL/UW-SSEEL.github.io#12]
We should backfill some posts for papers from the group, starting with the most recent first.

Files should follow this naming convention: yyyy-mm-dd-paper.md (e.g. 2009-02-20-facotrs-ox-reduc-SOFC.md) where the date is when the paper was published.

Files will follow a similar template as in #2 ***Note that any bracketed (<>) item should be filled with item-specific information (e.g. "<paper title>" replaced with "Factors Governing Oxygen Reduction in Solid Oxide Fuel Cell Cathodes")***

Contents in each file should follow

\---
layout: paper
title: "\<paper title>"
year: "\<year published>"
shortref: "\<citation>"
nickname: \<paper nickname>
journal: "\<publishing journal>"
volume: \<journal volume>
issue: \<journal issue>
pages: \<article pages>
authors: "\<author list>"
image: /assets/images/papers/\<paper image>.svg
redirect_from: 
fulltext: \<full text url> (optional)
pdf: \<pdf link> (optional)
pdflink: \<pdf link> (optional)
github: \<repository link> (optional
doi: "\< DOI number>" (e.g. "10.1149/1.3079337")
altmetric_id: \<altimetric ID number> (optional)
category: paper
\# Note: 'published' is a Jekyll keyword and does not refer to whether the paper is published, but rather to whether this Markdown should be part of the rendered site.
published: true
preprint: \<preprint status> (true or false)
embargo: false
peerreview: \<peer review status> (true or false)
review: \<review status) (true or false)
tags: [\<tag1>, \<tag2>]
\---
{% include JB/setup %}

\# Abstract 
\<abstract>

**Comment by BGerwe** [comment]
Addressed by bf278844561298f4559df2030526e37ebbee8d9a (papers 2019-2016) and bcd16c9e72012a3e4912477275f5a1ecdb511aaa (2016 Geary et al. paper and 2009 Lu et al. paper)

**Comment by BGerwe** [comment]
@giangtle Thanks so much for adding all of those papers! 🚀 

Do you think that's all of them?

**Comment by giangtle** [comment]
I think so. I'm pretty sure I got all the peer-reviewed ones from Stu [researchgate](https://www.researchgate.net/profile/Stuart-Adler-3). But I haven't doubled checked with google scholar yet.

**Comment by BGerwe** [comment]
That's good enough for me, great work! It's up to Stu if he wants to include any transactions papers on the site, but I suspect he won't.

I'm going to remove the "Under construction" tag at the bottom of the page and then close this.
