### ISSUE TITLE
Create .md files for each lab member

### ISSUE THREAD

**Issue by BGerwe** [UW-SSEEL/UW-SSEEL.github.io#2]
Every group member needs to create a file with their information, a short bio, and a headshot.

Files should follow this naming convention: yyyy-mm-dd-name.md (e.g. 2002-09-21-stu-adler.md) where the date is when each member joined the group.

Contents in each file should follow
***Note that any bracketed (<>) item should be filled with item-specific information (e.g. "\<member position>" replaced with "Graduate Student")***

\---
layout: _member_
title: "\<member name>"
position: \<member position>
nickname: \<member nickname> (optional)
handle: \<member handle> 
email: \<memberemail@uw.edu>
twitter: \<member twitter handle> (optional)
github: \<member github>
scholar: \<member Google Scholar ID> (bolded portion in: scholar.google.com/citations?user=***QDsxOlUAAAAJ&hl***=en&oi=ao)
image: /assets/images/team/\<member-picture>.png
cv: /assets/pdfs/\<member-cv>.pdf (optional)
alum: false
\---

\<member bio>

(e.g. Member is a graduate research assistant studying high temperature electric wiggles. They earned a B.S. in Chemical Engineering from \[Awesome University] in 1901. Outside of their studies, Member maintains a poorly subscribed \[YouTube Channel] about pet rock battles.

\[Awesome University]: http://www.awesome.edu
\[YouTube Channel]: http://www.youtube.com/channel/XXXYYYAAA!@#
)

**Comment by BGerwe** [comment]
Addressed by commits 1fce85ef52e0a1fc4db70925a96f1d262ac559db (Giang), 9f26688fddbcb4e7be345ec4c450a1b49d6f0653 (Giang), and bf278844561298f4559df2030526e37ebbee8d9a (Jon). Just need to add one for @MariaPoliti to finish active students. We'll worry about alumni later.

**Comment by BGerwe** [comment]
@giangtle is absolutely killing it with these website upgrades! 🎊  

We just need to add a page for @MariaPoliti and remove the "More Coming" placeholder before we can close this up.

**Comment by giangtle** [comment]
Added Maria's page!
